### ISSUE TITLE
Doesn't compile for NACL or Plan9

### ISSUE THREAD

**Issue by mholt** [onsi/ginkgo#622] opened 2019-11-15 21:19 UTC
`GOOS=nacl go build` returns these errors:

```
github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:220:33: undefined: syscall.SIGTERM
github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:245:33: undefined: syscall.SIGTERM
```

and `GOOS=plan9 go build` returns an error:

```
github.com/onsi/ginkgo/internal/remote/syscall_dup_unix.go:10:9: undefined: syscall.Dup2
```

This library is a dependency of [quic-go](https://github.com/lucas-clemente/quic-go) which we use in [Caddy](https://github.com/caddyserver/caddy) and Caddy can no longer compile for NACL or Plan9 because of this.

**Comment by Mohammed90** [comment] 2019-11-19 17:31
Ok, copying my comment from lucas-clemente/quic-go#2219:

> It's used in ginkgo here:
https://github.com/onsi/ginkgo/blob/ce5d301e555bb672c693c099ba6ca5087b06c0b4/internal/remote/output_interceptor_unix.go
It seems like it's being used as a buffer to intercept the output for inspection. Wouldn't stdlib's [pipe](https://golang.org/pkg/io/#Pipe) be useful here? I'm considering looking into doing it, but can't commit (and I'm aware this is the wrong repo to announce, but the issue is relevant). 

I had to submit the PR not as draft due to `ginkgo -r -p` constantly failing locally on a fresh `go get` with all deps available, so I had to take advantage of CI to help me debug.

My understanding of what's happening in the file ` internal/remote/output_interceptor.go` is that it's creating a temporary file and have it impersonate Std{out,err} using the `dup` syscall by taking the fd 1 and 2 so the file can receive writes that were meant for Std{out,err}. This way ginkgo can blindly write to stdout or stderr, and this will hijack the log in the background. Is my understanding right?

Here's where I'm at with the PR #627 ...

## Attempt 1:

After taking a jab at it, I opted for io.TeeReader instead of going with my hunch of using pipes, but it didn't exactly solve the issue. There were 2 failures.
- The first one:
```
• Failure [2.417 seconds]

Running Specs when running in parallel with -debug without -v [It] should emit node output to files on disk, without duplicating the GinkgoWriter output 

/home/travis/gopath/src/github.com/onsi/ginkgo/integration/run_test.go:321

  Expected

      <[]string | len:1, cap:1>: [

          "Running Suite: DebugParallelFixture Suite\n=========================================\nRandom Seed: 1574121921\nParallel test node 1/2.\n\n\nRan 0 of 0 Specs in 0.004 seconds\nSUCCESS! -- 0 Passed | 0 Failed | 0 Flaked | 0 Pending | 0 Skipped\nRunning Suite: DebugParallelFixture Suite\n=========================================\nRandom Seed: 1574121921\nParallel test node 2/2.\n\nDebugParallelFixture \n  emits output to a file\n  /tmp/ginkgo-run257609855/ginkgo/debug_parallel_fixture_test.go:11\n•\nRan 1 of 1 Specs in 1.016 seconds\nSUCCESS! -- 1 Passed | 0 Failed | 0 Flaked | 0 Pending | 0 Skipped\n",

      ]

  to have length 2

  /home/travis/gopath/src/github.com/onsi/ginkgo/integration/run_test.go:332

  Full Stack Trace

  testing.tRunner(0xc00015c700, 0xba6cd0)

  	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:909 +0x19a

  created by testing.(*T).Run

  	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:960 +0x652
```

- The second one:
```
• Failure [2.353 seconds]

Running Specs when running in parallel with -debug without -v [It] should emit node output to files on disk 

/home/travis/gopath/src/github.com/onsi/ginkgo/integration/run_test.go:303

  Expected

      <string>: Running Suite: DebugParallelFixture Suite

      =========================================

      Random Seed: 1574122084

      Parallel test node 1/2.

      

      DebugParallelFixture 

        emits output to a file

        /tmp/ginkgo-run650526053/ginkgo/debug_parallel_fixture_test.go:11

      GinkgoWriter 0

      GinkgoWriter 1

      GinkgoWriter 2

      GinkgoWriter 3

      GinkgoWriter 4

      GinkgoWriter 5

      GinkgoWriter 6

      GinkgoWriter 7

      GinkgoWriter 8

      GinkgoWriter 9

      •

      Ran 1 of 1 Specs in 1.014 seconds

      SUCCESS! -- 1 Passed | 0 Failed | 0 Flaked | 0 Pending | 0 Skipped

      Running Suite: DebugParallelFixture Suite

      =========================================

      Random Seed: 1574122084

      Parallel test node 2/2.

      

      

      Ran 0 of 0 Specs in 0.005 seconds

      SUCCESS! -- 0 Passed | 0 Failed | 0 Flaked | 0 Pending | 0 Skipped

      

  to contain substring

      <string>: StdOut 0

      

  /home/travis/gopath/src/github.com/onsi/ginkgo/integration/run_test.go:314

  Full Stack Trace

  testing.tRunner(0xc00015c700, 0xba6cd0)

  	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:909 +0x19a

  created by testing.(*T).Run

  	/home/travis/.gimme/versions/go1.13.4.linux.amd64/src/testing/testing.go:960 +0x652
```

Given the expectation of receiving 1 item instead of 2 in the first failure and not receiving `Stdout` in logging, I presumed it's an issue with intercepting writes to stdout. My understanding is intercepting stdout is done by impersonating its file descriptor as done by the `syscallDup` func. It went downhill from here.

## Attempt 2:

I tried `os.Pipe`. There was a nil pointer dereference due to mental lapse. I used the {read,write}Pipe wrongly there, but it still didn't make sense because the whole point is intercepting std{out,err} so Ginkgo can blindly use PrintX without worrying who the `io.Writer` is and still have the output intercepted by this. With this rationalization, I've abandoned this approach (probably prematurely).

## Attempt 3:

This time I decided to combine Std{out,err} using `io.MultiReader`. The issue with it is that it reads sequentially, so some tests didn't get the expected output due to their data not getting their turn to be read. The past sentence is complete speculation merely due to the actual output missing some expected output despite the writes to std{out,err} being merged with MultiReader.

This is where I'm at now with PR #627.

**Comment by Mohammed90** [comment] 2019-11-19 17:39
Also, umm.. not sure what to do with this 😅 

https://github.com/onsi/ginkgo/blob/39febac9157b63aeba74d843d6b1c30990f3d7ed/internal/remote/forwarding_reporter.go#L64-L65

**Comment by Mohammed90** [comment] 2019-11-21 20:32
The currently implemented approach (commit 3cfa02ded2d565a682638855d5f40dd9e00b6394 at the time of writing) is perhaps inspired by [this thread from one of Go's earlier issues](https://github.com/golang/go/issues/325). It's probably possible to maintain the current implementation, still remove tail in favor of probably TeeReader, and use [DuplicateHandle](https://golang.org/pkg/syscall/?GOOS=windows#DuplicateHandle) on Windows? I'll fiddle with it later and see what comes up.

**Comment by Mohammed90** [comment] 2019-11-23 17:19
The NaCl part, it's true that [Go's stdlib doesn't have SIGTERM for NaCl](https://golang.org/pkg/syscall/?GOOS=nacl#Signal). In searching for documentation on signals in NaCl, I found [this commit](https://codereview.chromium.org/1159803003/) adding SIGHUB and SIGTERM handlers in NaCl. This is beyond my field of knowledge, so my question is: is this for the process interacting with a NaCl process, or is it for within NaCl? The latter means Go's stdlib is missing an additional signal for NaCl in the syscall package.

**Comment by onsi** [comment] 2021-04-05 12:16
hey @Mohammed90 - sorry i never engaged on this.  I've got much more time to work on Ginkgo these days and am working on 2.0.  So the issue with NaCL/Plan9 is in how Ginkgo handles stdout/stderr redirection and the use of SIGTERM?  Do you know if that's all still true in 2021?  No worries if you've moved on from this and don't have any fresh context on it.

**Comment by Mohammed90** [comment] 2021-04-05 13:20
> hey @Mohammed90 - sorry i never engaged on this. I've got much more time to work on Ginkgo these days and am working on 2.0. So the issue with NaCL/Plan9 is in how Ginkgo handles stdout/stderr redirection and the use of SIGTERM? Do you know if that's all still true in 2021? No worries if you've moved on from this and don't have any fresh context on it.

No worries 🙂 Since quic-go has moved the ginkgo dependency to `_test`, we aren't blocked by this issue anymore. So it isn't a blocker for Caddy now. I don't know if it's impacting other users though.

**Comment by onsi** [comment] 2021-04-06 15:04
Thanks @Mohammed90 !

**Closed by onsi** 2021-04-06 15:04 UTC
Labels: waiting-for-response
