### ISSUE TITLE
flag provided but not defined: -test.timeout (Go 1.13)

### ISSUE THREAD

**Issue by dfreilich** [onsi/ginkgo#602] opened 2019-09-06 14:31 UTC
When trying to run the [apt-buildpack](github.com/cloudfoundry/apt-buildpack) integration tests on a computer running Go 1.13, we were unable to and got the following error: 
```

	 -------------------------------------------------------------------
	|                                                                   |
	|  Ginkgo timed out waiting for all parallel nodes to report back!  |
	|                                                                   |
	 -------------------------------------------------------------------

 integration timed out. path: .
[1] flag provided but not defined: -test.timeout
[1] Usage of /tmp/ginkgo538951234/integration.test:
...
```

Our integration test script:
```
#!/usr/bin/env bash
set -euo pipefail

cd "$( dirname "${BASH_SOURCE[0]}" )/.."
source .envrc
./scripts/install_tools.sh

GINKGO_NODES=${GINKGO_NODES:-3}
GINKGO_ATTEMPTS=${GINKGO_ATTEMPTS:-2}
export CF_STACK=${CF_STACK:-cflinuxfs3}

UNCACHED_BUILDPACK_FILE=${UNCACHED_BUILDPACK_FILE:-""}

cd src/*/integration

echo "Run Uncached Buildpack"
BUILDPACK_FILE="$UNCACHED_BUILDPACK_FILE" \
  ginkgo -r -mod vendor --flakeAttempts=$GINKGO_ATTEMPTS -nodes $GINKGO_NODES --slowSpecThreshold=60 -- --cached=false
```

Env:
```
root@b349d15677b6:/app# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/app/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build280745408=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by dfreilich** [comment] 2019-09-06 14:32
Suspect this is the cause https://golang.org/doc/go1.13#testing

> Testing flags are now registered in the new Init function, which is invoked by the generated main function for the test. As a result, testing flags are now only registered when running a test binary, and packages that call flag.Parse during package initialization may cause tests to fail.

**Comment by lempiy** [comment] 2019-09-11 07:32
Getting the same issue after upgrade to Go 1.13:
```bash
./bin/ginkgo -cover -r ne -- -c /builds/cns/go-app/conf/main.conf -override /builds/cns/go-app//conf/main.override.conf.tpl -override-type template -env test
flag provided but not defined: -test.timeout
```

**Comment by Winterhart** [comment] 2019-09-26 17:22
I am having the same bug right now. a `Darwin` `amd64` architecture

**Comment by mszostok** [comment] 2019-11-07 20:58
any update? are you planning to fix that?

**Comment by zhubuntu** [comment] 2019-11-19 10:50
I met the same problem

**Comment by lempiy** [comment] 2019-11-19 13:16
In some cases explicit call for `testing.Init()` before init() functions may help:
```go

var _ = func() bool {
 	testing.Init()
	return true
}()

func TestDatabase(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "App / Suite")
}

```

**Comment by ansd** [comment] 2019-11-21 23:10
As @dfreilich correctly pointed out, the `flag provided but not defined` error occurs because of https://golang.org/doc/go1.13#testing:
> packages that call flag.Parse during package initialization may cause tests to fail

It occurs when `flag.Parse` is called within the `init` function.
The solution is to move `flag.Parse` from the `init` function to somewhere else (e.g. to `main` or `BeforeSuite`)
For the example above [this line](https://github.com/cloudfoundry/apt-buildpack/blob/7323b8667e832b7b40761635393a4513758b6d5d/src/apt/integration/integration_suite_test.go#L30) must be moved.

An example how to reproduce this error without using ginkgo can be found [here](https://github.com/golang/go/issues/31859#issue-440718028).
(I can reproduce it with the latest `go version go1.13.4 darwin/amd64`.)

I agree with @zhubuntu that this is not a Ginkgo issue.
I therefore suggest to close this issue.

**Comment by blgm** [comment] 2019-11-27 17:18
Looks like it’s a breaking change in Go 1.13. The solution is for users not to call `flag.Parse()` in an `init()` function. Please let us know if that does not work for you.

**Closed by blgm** 2019-11-27 17:18 UTC
Labels: bug

**Comment by antoineco** [comment] 2019-11-28 09:49
I can confirm that replacing
```go
func init() {
	flag.Parse()
}

TestXYZ(t *testing.T) {}
```
with
```go
func TestMain(m *testing.M) {
	flag.Parse()
	os.Exit(m.Run())
}

TestXYZ(t *testing.T) {}
```

**Comment by puppet-py** [comment] 2020-06-17 18:39
I am hitting this error `flag provided but not defined: -test.timeout `without having to use the `flag.Parse` anywhere in my codebase. Nor there is any `init` func
My env:
```
$ go version
go version go1.13.3 darwin/amd64
$ ginkgo version
Ginkgo Version 1.12.3
```

**Comment by blgm** [comment] 2020-06-17 20:23
@puppet-py, could you share a little more context about what triggered this. Have you just upgraded something? Have you added some more code? How long is it since things worked without getting this error? Is there an easy way to reproduce it that you can share?

`test.timeout` is in the Ginkgo codebase, so we should absolutely be suspicious of Ginkgo. The challenge is to work out why you are seeing it, but most other users are not.

**Comment by puppet-py** [comment] 2020-06-17 21:45
@blgm You can refer the last comment here https://github.com/onsi/ginkgo/issues/693#issuecomment-645523206 wrt my findings. @onsi was earlier responding to that issue which I have opened

**Comment by zemul** [comment] 2020-08-20 03:31
before flag.Parse()   add testing.Init()

**Comment by blgm** [comment] 2020-08-20 07:05
Hi @zemul. Could you say a bit more about the issue that you're having?

**Comment by patelpayal** [comment] 2020-09-02 21:42
I am running into the same issue. I am using go 1.13 for the build environment. 

I added `test.Init()` before `flag.Parse()` but still running into the same issue.  ```flag provided but not defined: -timeout```

Any suggestions?

**Comment by blgm** [comment] 2020-09-03 08:53
@patelpayal, there is a suggested approach here: https://github.com/onsi/ginkgo/issues/602#issuecomment-557313846

**Comment by ltx0621** [comment] 2021-05-10 03:23
I've encountered this error log while using branch v2:
`flag provided but not defined: -ginkgo.timeout`

steps:
1. git clone and checkout branch v2 ,go build
2. run the cli command , `./ginkgo` , no option.

go version `go version go1.16.3 darwin/amd64`
 
ps: the case run perfectly with master branch

**Comment by onsi** [comment] 2021-05-10 03:29
hey thanks for giving V2 a try.  can you confirm that you recompiled the `ginkgo` binary (eg run `ginkgo version`).  I suspect you're using an older version of the cli.
