### ISSUE TITLE
ginkgo sets the current working directory to where the test suite is

### ISSUE THREAD

**Issue by attila123** [onsi/ginkgo#432] opened 2018-02-14 18:33 UTC
I start 'ginkgo -r' in the root directory of my project and I would assume that the current working directory does not change. However, it seems to change the working directory to whichever directory I move my test suite file to (currently I am writing my first test suite).
To print the current working directory something like this can be used (I printed it in my BeforeSuite).
```
pwd, err := os.Getwd()
log.Println("os.Getwd():", pwd, err)
```
This is problematic, because I would like to load certain test files relative to my project's working directory, and currently it seems that I need to write some logic to guess my project's root directory, and use it to load the test resource files using their absolute path.

Update: this may be because https://stackoverflow.com/questions/23847003/golang-tests-and-working-directory
I will check this tomorrow.

Environment:
$ ginkgo version
Ginkgo Version 1.4.0
$ go version
go version go1.9.3 linux/amd64

**Comment by cdrage** [comment] 2019-10-23 13:30
Hey @attila123 were you ever able to write a test that would work-around using the current working directory? Like you, I need to write a text that will "fake" and be a different working directory..

**Comment by blgm** [comment] 2019-10-23 16:16
The `-r` flag recurses by changing into subdirectories as a features of how it was designed. This is also how `go test ./...` behaves.

I see how it makes it awkward to load test fixtures that are shared between different packages because you end up referring to them via paths like `"../shared-fixtures"` or writing the code that you describe. I can imagine an environment variable could be used to help with this. Potentially there could be a future feature to help.

I don't think it would be practical to change the behaviour of Ginkgo in this regard because it would break many existing users. Ginkgo tests can also be run by running `go test ./...` so it's very desirable to behave in a consistent way with `go test`.

I'm going to close this for now because we can't change a fundamental behaviour like this without having lots of unhappy users. But if anyone has any clever ideas of how we can achieve the same aims without breaking existing users, then please feel free to add them, raise a new issue, or a PR.

**Closed by blgm** 2019-10-23 16:16 UTC

**Comment by attila123** [comment] 2019-10-24 11:18
@cdrage I don't work on this project any more for some time, but I managed to dig up the code what I did:

```
func getProjectRootPath(projectRootDir string) string {
	log.Println("### getProjectRootPath is running")
	cwd, err := os.Getwd()
	cwdOrig := cwd
	if err != nil {
		panic(err)
	}
	for {
		if strings.HasSuffix(cwd, "/"+projectRootDir) {
			return cwd
		}
		lastSlashIndex := strings.LastIndex(cwd, "/")
		if lastSlashIndex == -1 {
			panic(cwdOrig + " did not contain /" + projectRootDir)
		}
		cwd = cwd[0:lastSlashIndex]
		log.Println("cwd", cwd)
	}
}
```

The code may be a bit messy (it was my first and so far last project in Go), but what I did is to get the current directory, and then keep stepping back to parent dirs until it finds a constant string of `projectRootDir` at the end of the directory name. For me this was something like:
`var projectRootDir = "test-tools/foo-bar"`
(use the directory of your project)
Hope this helps.
