### ISSUE TITLE
Reports not getting generated

### ISSUE THREAD

**Issue by marianopinto** [onsi/ginkgo#862] opened 2021-11-17 17:11 UTC
### Setup
- CI/CD Jenkins
- Aws Lambda to actually run the test (the Ginkgo command to run the tests is baked in the lambda)
- Internal tool built to trigger the lambda

### Execution
The lambda gets built together with the above mentioned tool, the ginkgo executale and the packaged tests of course. Jenkins is where the tests actually run.

### Issue
After migrating to v2 I am seeing the tests running fine on my machine but the reporting part is failing on Jenkins. The following error message is being logged:
```autogenerated by Ginkgo

  Begin Captured GinkgoWriter Output >>
    [ReportAfterSuite] TOP-LEVEL
      autogenerated by Ginkgo
  << End Captured GinkgoWriter Output

  Failed to generate JSON report:
  open junit.xml: read-only file system
  In [ReportAfterSuite] at: /Users/<user>/go/pkg/mod/github.com/onsi/ginkgo@v1.16.6-0.20211115182015-aec53805973a/reporting_dsl.go:127
  ```
  
### Generating reports
In Ginkgo v1 I was using the Junit reporter and the reports were getting generated and then stored in the `/tmp` folder of the lambda function. I am trying to do the same thing now with the difference that I am leveraging the new command line arguments offered in v2 such as `--junit-report` and `-output-dir`. The Junit plugin then retrieves the files and make the reports available in Jenkins itself.

### Next Steps
I am happy to provide support to investigate this. It might just be a misconfiguration I made or maybe there's something else.

**Comment by onsi** [comment] 2021-11-17 18:02
thanks for the details - can you share which command line flags you're using?  I think the issue is that Ginkgo stores the reports in the package directories before moving them to `output-dir` and the package directories aren't writable in the environment in question. But knowing what flags you're using will help me pin things down a bit more.

**Comment by marianopinto** [comment] 2021-11-17 22:12
Hi @onsi, this is the command I use to run the tests:
```ginkgo --junit-report=out.xml -no-color --nodes=40 --timeout=15m -slow-spec-threshold='60s' --succinct --trace --progress --flake-attempts=2 -output-dir=/tmp/reports```

**Comment by onsi** [comment] 2021-11-17 22:15
ok thanks.  right now the reporting infrastructure puts intermediate assets in the package directories and then moves them to the output-die afterwards.  i'm changing it so that if output-dir is specified all assets go there directly.  there are a few edge cases to handle but i'm hoping to have the fix out by tomorrow.

**Comment by marianopinto** [comment] 2021-11-17 22:18
Thanks a lot for your hard work @onsi.

**Comment by onsi** [comment] 2021-11-18 18:10
hey @marianopinto please give the latest code on `ver2` a try.  This should be fixed now.

**Comment by marianopinto** [comment] 2021-11-19 21:12
Hi @onsi, thanks for the quick turnaround on this. I gave it a go and it seemed to be working. Unfortunately I was not able to test it in the CI yet as I noticed that the major version number of Ginkgo has been bumped to v2 and I want to update that as well. Hopefully I'll be providing you feeedback on this very soon.

**Comment by onsi** [comment] 2021-11-19 21:13
Perfect, thanks!

**Comment by marianopinto** [comment] 2021-11-19 21:47
Hi again @onsi, quick one regarding the new version. I was told that a few people are having issues while running `go get github.com/onsi/ginkgo/v2@2.0.0-rc2` getting this `go get: github.com/onsi/ginkgo/v2@2.0.0-rc2: invalid version: unknown revision 2.0.0-rc2` back. Are you aware of what could be causing this? Thanks

**Comment by marianopinto** [comment] 2021-11-22 15:17
Hi @onsi, I can finally confirm that the fix is working as expected. Running smooth in Jenkins and reports getting generated correctly. Thanks

**Closed** 2021-11-22 15:17 UTC
