### ISSUE TITLE
continue after failure in ordered container

### ISSUE THREAD

**Issue by pohly** [onsi/ginkgo#966] opened 2022-04-20 08:47 UTC
When running specs in an ordered container, ginkgo aborts after the first test failure:
```
  Spec skipped because an earlier spec in an ordered container failed
```

In my case, additional specs can run. I need them to run in a certain order not because there are dependencies between them (each spec is self-contained) but because it is more efficient (some setup code can get skipped) and some tests are more reliable when run first.

Is it possible to configure whether ordered containers fail fast?

### Background

I am testing PMEM-CSI with ginkgo and started the migration to v2 there. I'm also helping with Kubernetes and csi-test, which need to be migrated first.

In PMEM-CSI, we have the problem that one of our dependencies, the Operator Lifecycle Manager (OLM) fails with random timeouts when the tests using it run after the test cluster has been used for a while. I don't have a good explanation and clearly that shouldn't happen. I suspect some performance degradation, but the only solution that I have found so far is to run the tests with OLM directly after bringing up a test cluster.

**Comment by pohly** [comment] 2022-04-20 08:50
In Ginkgo v1, is execution order deterministic when parallelization and randomization are off? I had the impression that it runs in the order in which specs are defined, but that didn't work all the time.

Obviously using Ginkgo v2 with explicit semantic will be better, it just might take a while longer to get there :sweat_smile:

**Comment by onsi** [comment] 2022-04-26 17:10
hi @pohly - am finally feeling better so I'll work through the various issues you've opened and share some replies.

> Is it possible to configure whether ordered containers fail fast?

it is not possible to configure whether ordered containers fail fast - and I'm trying to avoid adding more caveats and knobs to the ordered container stuff so I'd prefer to not make too many changes there.

> In Ginkgo v1, is execution order deterministic when parallelization and randomization are off? I had the impression that it runs in the order in which specs are defined, but that didn't work all the time.

In both Ginkgo v1 and Ginkgo v2 you cannot turn off randomization.  However, the [default behavior](https://onsi.github.io/ginkgo/#spec-randomization) when running in series is to only shuffle the order of the outermost container nodes unless you add the `--randomize-all` flag in which case all the individual `It`s are shuffled.  When running in parallel no spec order guarantees are made unless you explicitly opt into `Ordered` containers.

In a sense, all this behavior is intentional to help surface and identify precisely the kind of flaky behavior you're seeing with your OLM failures.  Unfortunately without knowing much more detail about your setup I don't have too many helpful suggestions.  Though figuring out why the system under test is flaky, and resolving _that_ is probably the best long-term solution.

**Comment by pohly** [comment] 2022-04-26 18:49
> it is not possible to configure whether ordered containers fail fast - and I'm trying to avoid adding more caveats and knobs to the ordered container stuff so I'd prefer to not make too many changes there.

Would you accept a PR?

> In a sense, all this behavior is intentional to help surface and identify precisely the kind of flaky behavior you're seeing with your OLM failures. Unfortunately without knowing much more detail about your setup I don't have too many helpful suggestions. Though figuring out why the system under test is flaky, and resolving that is probably the best long-term solution.

Unfortunately OLM is not something that any of the developers working on PMEM-CSI are familiar with, and the upstream OLM developers have shown little interest in helping us with debugging problems that only occur in our CI system.

**Comment by onsi** [comment] 2022-04-26 19:13
> Would you accept a PR?

Sorry - I wasn't trying to communicate "this is complicated so I don't have time to do it."  I was trying to say "there's already growing code _and_ function.l complexity to this feature and I don't want to make it more complex."  As it stands I'm seeing all sorts of interesting uses of `Ordered` trying to paper over the reality that the system under test actually needs improvement.

I appreciate that doesn't necessarily help you.  And I do want to help - I'd love to explore alternatives, though (this is where a zoom call could be handy).  Are there other ways to set up the test suite/scenario to ensure non-flaky/less-flaky behavior?

**Comment by pohly** [comment] 2022-04-26 19:31
> Are there other ways to set up the test suite/scenario to ensure non-flaky/less-flaky behavior?

I could invoke it twice, with different -ginkgo.focus/skip parameters. It would make an already complex invocation even more complex, but it would be doable.

**Comment by onsi** [comment] 2022-04-26 19:41
Right.  But if invoking it twice is an option then why not have the flaky "need to run right away" specs use their own dedicated resource/cluster and have all the others use a different one.  The cost of setting up both clusters is the same for either scenario.

I'd love to do a deeper dive with you and whoever else is close to these test suites as I do wonder if there are alternatives like this that could make the suites more robust and (potentially) more performant.

**Comment by pohly** [comment] 2022-04-26 19:57
> The cost of setting up both clusters is the same for either scenario.

True, but reusing the same cluster is more efficient. We are trying to save some money here.

> I'd love to do a deeper dive with you and whoever else is close to these test suites as I do wonder if there are alternatives like this that could make the suites more robust and (potentially) more performant.

Thanks for the offer to help, but I think I can solve this myself.

**Comment by onsi** [comment] 2022-04-26 20:00
okie doke :) if you do end up wanting to revisit it let me know.  sorry there aren't any out-of-the-box solutions that Ginkgo can offer.

**Comment by dmytro-zakharov** [comment] 2022-04-27 09:47
Hey!
I found this issue as I have a similar problem that I'm not sure how to solve.
First of all - I've just started using ginkgo and everything looks promising, but I may have missed something 😬 

I want to run some integration tests on a running test environment and check if a result of some action impacts correctly all the services. Every check is independent, so I'd love to have an option to "continue execution if something fails".

My use case is: User has some credits and makes a payment. I want to check that once a payment succeeds, his balance is correctly updated in service A, a record has been created in services B and C. Communication between services is asynchronous, so the order of actions does not really matter.

So far I ended up with a structure like this, using `Ordered` to be able to run `BeforeAll`:

```go
var _ = Describe("User pays", Ordered, func() {
	When("an account is active", func() {
		var paymentID string
		var previousBalance int
		paymentAmount := 1

		BeforeAll(func() {
			// setup seeds
			CreateAccount()
			CreditAccount()
			// here is an action to test
			paymentID = MakePayment()
		})

		It("updates balance in service A", func() {
			Expect(account.Balance()).To(Equal(previousBalance - paymentAmount))
		})

		It("creates a record in service B", func() {
			Expect(serviceA.FindRecordByPaymentID(paymentID)).To(Exist())
		})

		It("creates a record in service B", func() {
			Expect(serviceB.FindRecordByPaymentID(paymentID)).To(Exist())
		})
	})
})
```

Do you have any suggestions how can I continue tests execution if an `it` fails?

**Comment by pohly** [comment] 2022-04-27 09:53
What do you need `Ordered` for in this example? It looks like you can simply drop it.

**Comment by dmytro-zakharov** [comment] 2022-04-27 09:59
As I mentioned - to be able to use `BeforeAll`. Once I remove `Ordered`, I get this error:

```
Setup Node not in Ordered Container
BeforeAll(func() {
  [BeforeAll] setup nodes must appear inside an Ordered container.  They cannot
  be nested within other containers, even containers in an ordered container.

  Learn more at: http://onsi.github.io/ginkgo/#ordered-containers
```

**Comment by pohly** [comment] 2022-04-27 10:12
Can't you use a normal `BeforeEach`? Or is the setup so expensive that it should only run once?

**Comment by dmytro-zakharov** [comment] 2022-04-27 10:40
A normal `BeforeEach` might be an option, but since the setup is relatively expensive and may slow down the whole execution - it seemed to be more natural to rely on a single run using `Ordered` / `BeforeAll`, but maybe I miss some hidden drawbacks with `BeforeAll` approach 🤔

**Comment by onsi** [comment] 2022-04-27 15:39
hey @dmytro-zakharov Ginkgo lets you make the following trade-off:

- Build [independent specs](https://onsi.github.io/ginkgo/#mental-model-ginkgo-assumes-specs-are-independent) that can be parallelized and randomized.  This is the recommended approach and avoids using `Ordered` containers.  You can amortize the cost of setup in a variety of ways (happy to dig into it further with you if interested) and by parallelizing your suite you can generally keep test performance reasonable.

- Build [ordered specs](https://onsi.github.io/ginkgo/#ordered-containers) that allow you to express more complex flows as distinct `It`s.   In effect, the specs in an `Ordered` container behave like one large `It` (in fact, people used to write these as one large `It` but asking for a `BeforeAll` became a common refrain in the community so I introduced `Ordered` containers to help people break up their specs into more bite-sized chunks).

Ginkgo's opinion is that when a spec in an `Ordered` container fails the entire container is considered suspect and no subsequent specs will run.  While I can imagine adding complexity to allow users to specify "but not _this_ spec" I'm concerned that that will make the behavior of `Ordered` containers even harder to reason about.  My preference is to guide users to prefer independent specs over correlated specs and to use `Ordered` only in the specific context it was intended for: breaking up large complex `It`s into smaller pieces to make the test a bit easier to read.

**Comment by pohly** [comment] 2022-04-27 16:41
For comparison, when doing unit tests and assertions with github.com/stretchr/testify, one can do some complex work, then check multiple aspects of the result with github.com/stretchr/testify/assert. Failures will be recorded, but testing continues. When passing a check is essential for continuing to test, then github.com/stretchr/testify/require records a failure and aborts.

Ginkgo supports only the latter.

**Comment by onsi** [comment] 2022-04-27 16:49
Correct - Ginkgo supports only the latter and that choice is intentional and stems from Ginkgo's origin story as a framework to enable TDD.

**Comment by pohly** [comment] 2022-04-27 18:18
> However, the [default behavior](https://onsi.github.io/ginkgo/#spec-randomization) when running in series is to only shuffle the order of the outermost container nodes 

This hint allowed me to solve my problem in PMEM-CSI: I moved the `Describe` calls from top-level into a `Context` and now they get executed in the order in which they are defined because `--randomize-all` is off.

As far as I am concerned, this issue can be closed.

**Closed** 2022-04-27 18:22 UTC
