### ISSUE TITLE
Enable cpuprofiling 

### ISSUE THREAD

**Issue by niranjankl** [onsi/ginkgo#201] opened 2015-12-07 09:46 UTC
Hi,
I would like to know how to enable cpu/mem profile for ginkgo. I really would like to use it along with -Nodes option.

Thanks,
Niranjan KL

**Comment by robdimsdale** [comment] 2016-01-31 19:59
@niranjankl as far as I'm aware the only profile that ginkgo supports is test coverage. It sounds like you're proposing a feature request where ginkgo can optionally report CPU and memory profiling, perhaps writing it to a file like the cover profiling.

Reading between the lines, it sounds like you're running tests in parallel with `-nodes` and would like to correlate that with CPU and memory performance? Are you running into actual performance issues like memory and CPU being maxed-out? Or is this more for curiosity, perhaps you're trying to optimize the number of nodes to run in parallel?

For now you could make use of 3rd-party utilities for these kinds of metrics. I get a lot of value of out [htop](http://hisham.hm/htop/)

**Comment by niranjankl** [comment] 2016-02-01 09:18
@robdimsdale thanks a lot for your inputs. We use ginkgo as unit testing framework extensively and I thought it would be great if we can collect performance metrics using ginkgo itself.

**Comment by robdimsdale** [comment] 2016-02-01 14:52
Ok, thanks for clarifying. I haven't yet found a situation where profiling unit tests would need helpful, but if you wanted to submit a PR to support this I expect we would take it.

I don't have a clear idea as to how one might implement that, but I might start by looking at https://golang.org/pkg/net/http/pprof/

If this is something you are interested in working on let's use this issue to drive out the implementation.

**Comment by seanschade** [comment] 2016-10-14 18:35
It looks like Ginkgo doesn't support all of the testing flags. I have benchmarks for which I want the cpu and memory profiles for. However, it seems these flags are ignored. 

https://golang.org/cmd/go/#hdr-Description_of_testing_flags

**Comment by onsi** [comment] 2016-10-15 01:00
are you on head?  i believe this commit:

https://github.com/onsi/ginkgo/commit/120efcfd33906beedc53369a8659c41cc9190e81

pulled this in...

**Comment by onsi** [comment] 2016-10-15 01:01
(don't forget to rebuild the ginkgo cli after you pull)

**Comment by Burr** [comment] 2016-12-15 00:54
We are having the same problem. I don't believe that referenced commit (120efcf) solves the issue.

I believe the root cause is that running the tests is a two step operation: 

1) Compile the code into a temporary path - https://github.com/onsi/ginkgo/blob/master/ginkgo/testrunner/test_runner.go#L124
2) Run the tests against the path - https://github.com/onsi/ginkgo/blob/master/ginkgo/testrunner/test_runner.go#L250

Currently the changes in the referenced commit (120efcf) only affect step 1. So it does pass in the "cpuprofile" flag there. However, since it's just compiling, not actually running the tests, the argument is effectively ignored by `go test`.

There would need to be a change to pass in the args to the actual running of the test (in the `cmd` function) for the profile to be passed on and acted on by `go test`.

**Comment by onsi** [comment] 2016-12-21 04:35
hmm :/ fair point.  @Burr are you up for submitting a PR?

**Comment by Burr** [comment] 2016-12-22 04:06
Sure, I'll take a look at it and see if I can figure out a clean way to proceed. If so, I'll submit a PR. Thanks!

**Comment by onsi** [comment] 2017-06-07 15:17
I believe this was fixed with #282

**Closed by onsi** 2017-06-07 15:17 UTC
