### ISSUE TITLE
ginkgo installation failed by Dep

### ISSUE THREAD

**Issue by junpayment** [onsi/ginkgo#513] opened 2018-07-27 04:50 UTC
Hi contributers, thanks a great product!

Attempting to install with dep will fail.

```bash
$ dep ensure
 :
(21)  ? attempt gopkg.in/fsnotify.v1 with 1 pkgs; 0 versions to try
panic: version queue is empty, should not happen
 :
```

Actually I know the cause, I also know how to avoid it.

This is because the path of `gopkg.in/fsnotify/fsnotify.v1` referred to by kinkgo's dependent library `github.com/hpcloud/tail` at `v1.0.0 (latest)` is different from the current one .

*I make the issue about it*
https://github.com/hpcloud/tail/issues/146

*fsnotify*
https://gopkg.in/fsnotify.v1

The workaround is as follows.

### Switch `source` in`gopkg.in/fsnotify/fsnotify.v1`

Write `Gopkg.toml` like below

```toml
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"
```

see also https://github.com/golang/dep/issues/1799#issuecomment-381026769

### Use the master branch of `github.com/hpcloud/tail`

Write `Gopkg.toml` like below
Because master branch of `tail` already solved it.

```toml
[[override]]
  branch = "master"
  name = "github.com/hpcloud/tail"
```

I hope to solve the root cause if possible.
Because I think that dep is still used so much and it can be predicted what vgo will be going on so I think that many users rely on dep.

**Comment by nodo** [comment] 2018-08-01 16:41
Hey @junpayment !

Thanks for reporting this problem and investigating the root cause! Hopefully, it will help other `ginkgo` users with the same problems.

I feel that this issue is not related to `ginkgo` directly and for now I am going to close it. Please, feel free to re-open the issue if you have questions or comments on this.

**Closed by nodo** 2018-08-01 16:41 UTC
