### ISSUE TITLE
Leaves hanging processes

### ISSUE THREAD

**Issue by momchil-sap** [onsi/ginkgo#237] opened 2016-03-18 14:50 UTC
Hi,

It seems that when using the `exec` package from within Ginkgo tests, it's possible to end up with a hanging process. Let me give an example.

I have the following script file. It prints the current date twice a second.

```bash
#!/bin/bash
set -e
while true; do
	current_date=`date`
	echo "Date: ${current_date}"
	sleep 0.5
done
```

If I run the following go program, I have no problems and the shell script is regularly started and stopped with `SIGTERM`.

```go
package main

import (
	"fmt"
	"os"
	"os/exec"
	"syscall"
	"time"
)

func main() {
	for i := 0; i < 100; i++ {
		fmt.Println("Starting test.sh...")
		cmd := exec.Command("./test.sh")
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		err := cmd.Start()
		panicOnErr(err)

		fmt.Println("Sleeping...")
		time.Sleep(time.Second)

		fmt.Println("Stopping test.sh...")
		err = cmd.Process.Signal(syscall.SIGTERM)
		panicOnErr(err)
		cmd.Wait()
	}
}

func panicOnErr(err error) {
	if err != nil {
		panic(err)
	}
}
```

If I run the following Ginkgo test with `ginkgo -r --untilItFails`, it eventually hangs. (It could take a while - ~ `30` iterations)

```go
package main_test

import (
	"os"
	"os/exec"
	"syscall"
	"time"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

var _ = Describe("Main", func() {
	var cmd *exec.Cmd

	BeforeEach(func() {
		cmd = exec.Command("./test.sh")
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		err := cmd.Start()
		Ω(err).ShouldNot(HaveOccurred())
	})

	AfterEach(func() {
		err := cmd.Process.Signal(syscall.SIGTERM)
		Ω(err).ShouldNot(HaveOccurred())
		cmd.Wait()
	})

	It("should pass", func() {
		time.Sleep(time.Second)
	})
})
```

What happens is that the `AfterEach` hangs, leaving the `test.sh` process to continue to run. What is more interesting is that running a `kill <pid>` command from the terminal does not stop the `test.sh` process. You need to forcefully kill the `test.sh` process.

I believe this is the reason for the following Agouti issue: https://github.com/sclevine/agouti/issues/65

**Comment by odlp** [comment] 2016-03-23 17:55
@momchil-sap seems like we're having a similar issue, after upgrading to Go 1.6. Which version are you using?

**Comment by onsi** [comment] 2016-03-26 20:07
hey @momchil-sap your examples are subtly different.  `--untilItFails` runs the compiled test binary many times whereas your `main.go` program invokes the binary in a for loop.  Not sure if it makes a big difference but it might be good to compile `main` and run it in a loop (e.x. with bash or - to be even more faithful - by invoking it in a loop from another go program) to see how it behaves.

I'm not sure how this can be an issue in Ginkgo :/  if you have any thoughts on what Ginkgo might be doing here I'd love to hear it.  But I suspect this might be a regression in go 1.6?  Maybe?

**Comment by momchil-sap** [comment] 2016-03-28 06:29
@onsi @odlp I think the same would occur on `1.5` as well.

I did the experiment with a `main` that runs `test.sh` that is called by another `main` in a loop. Could not reproduce it.

**Comment by robdimsdale** [comment] 2016-04-27 02:10
@momchil-sap did you get chance to try this on golang 1.5? It sounds like you can't reproduce this on go 1.6 anymore? I'm a little confused as to whether this is still causing issues for you?

**Comment by momchil-sap** [comment] 2016-04-27 06:09
Hi @robdimsdale , I could reproduce this with `golang 1.6` and I believe it was reproducible with `golang 1.5.2` as I had similar issues before. I have not tried with `1.6.2` to see if something has changed.

I will check and get back to you.

**Comment by momchil-sap** [comment] 2016-04-27 12:43
@robdimsdale I spent a considerable amount of time trying to reproduce this again but couldn't.

I could not get the desired result even once on my personal laptop, which has the latest versions of `Go`, `ginkgo` and `gomega`. I tried using different versions of Go (`1.5.2`, `1.5.4`, `1.6`, `1.6.1`, `1.6.2`), Ginkgo and Gomega but to no avail.

I moved to a workstation that had older versions of the software, just to double-check. There I had Go `1.6.1` and older revisions of Ginkgo and Gomega - from around December.

I managed to reproduce it twice, after which I decided to update Ginkgo and Gomega to see if that will change the outcome. It did, as I could no longer reproduce the problem. I tried rolling back to the older versions that I had noted down but that did not help as tests would now run successfully. I made sure to delete the `$GOPATH/pkg` and `$GOPATH/bin` folders just in case. I even rolled-back the only dependency I could find - `protobuf` - to an older version as well.

I am really confused at the results I get. I start to worry that it might be the anti-virus software playing games with me or something of that kind.

If you have any idea what I could have unknowingly updated by bumping Ginkgo and Gomega that I should roll back, I would be happy to hear it.

An alternative is to trust (rather hope) that with the latest software the problem is just gone, not to try and investigate it any further, and close the issue. I am personally ok to give it one more try some other day with a clear head, before closing it for good.

**Comment by robdimsdale** [comment] 2016-05-20 19:10
@momchil-sap did you ever manage to figure this out? I'm happy to close the issue if you didn't make any more progress

**Comment by momchil-sap** [comment] 2016-05-30 06:20
No luck. @robdimsdale, I guess you can close it. If I ever do reproduce it, I could open a new one and link to this one.

**Comment by robdimsdale** [comment] 2016-05-30 14:25
Absolutely, sounds great. Thanks for checking in again - much appreciated.

**Closed by robdimsdale** 2016-05-30 14:25 UTC
