### ISSUE TITLE
Test starts flaking after a bump to ginkgo v1.5.0 and gomega v1.4.0

### ISSUE THREAD

**Issue by teddyking** [onsi/ginkgo#482] opened 2018-06-04 08:56 UTC
We recently bumped our ginkgo/gomega dependencies as follows:

Ginkgo -> From: `059cec02d342bab423425a99b191186a03255e9e` to `v1.5.0`
Gomega -> From: `0df7b7fdb38123c12a1f569f0affb2c2a7bd72cf` to `v1.4.0`

After the bump one of our tests has started to flake.

The flakiness can be easily reproduced by focusing [this Context](https://github.com/cloudfoundry/garden-shed/blob/4f5659ae4eb0d049ca0fd7337694672c9f5046b9/layercake/docker_linux_test.go#L269-L348) and running across parallel GinkgoNodes (it may take a few runs to flake, but we've consistently seen it flake in under 10 runs on the newer versions of ginkgo/gomega).

My guess is that maybe something has changed with how variables are scoped/handled in Before/JustBefore/After Eaches? Are you aware of anything that could've changed like this?

@williammartin has some context / can help in running the tests to reproduce the flake.

**Comment by williammartin** [comment] 2018-06-04 09:07
What is the failure that you see? If someone looks at this I guess they're going to want to know they are reproducing the same failure you are seeing.

**Comment by teddyking** [comment] 2018-06-04 10:10
Full steps to reproduce:

```
# clone garden-runc-release
git clone https://github.com/cloudfoundry/garden-runc-release.git
cd garden-runc-release

# checkout version of `garden-runc-release` which includes the updated versions of ginkgo/gomega
git checkout 428987a50b71a418f21621ee802be098fe46c541
git submodule update --init --recursive

# focus the context mentioned above in `src/code.cloudfoundry.org/guardian/vendor/code.cloudfoundry.org/garden-shed/layercake/docker_linux_test.go`

# run the tests
export GARDEN_REMOTE_ATC_URL=<concourse target>
scripts/remote-fly ci/unit-tests/shed.yml -- -untilItFails layercake
```

And the exact failure is:

```
**• Failure [1.432 seconds]
Docker QuotaedPath when using aufs quotaed driver [It] should not allow the user to write that exceeds the quota
/tmp/build/e55deab7/gr-release-develop/src/code.cloudfoundry.org/guardian/vendor/code.cloudfoundry.org/garden-shed/layercake/docker_linux_test.go:340

  Expected error:
      <*errors.errorString | 0xc420418080>: {
          s: "getting mountpath: error creating aufs mount to /tmp/cakeroot195755475/aufs/mnt/ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad: invalid argument",
      }
      getting mountpath: error creating aufs mount to /tmp/cakeroot195755475/aufs/mnt/ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad: invalid argument
  not to have occurred

  /tmp/build/e55deab7/gr-release-develop/src/code.cloudfoundry.org/guardian/vendor/code.cloudfoundry.org/garden-shed/layercake/docker_linux_test.go:342**
```

We think the error may be the result of a "missing" layer required to perform the mount because it has accidentally been cleaned up. E.g. the "root" variable looks a bit suspicious given it's defined [here](https://github.com/cloudfoundry/garden-shed/blob/master/layercake/docker_linux_test.go#L38), used in both the "upper" BeforeEach [here](https://github.com/cloudfoundry/garden-shed/blob/master/layercake/docker_linux_test.go#L53-L54) and "lower" BeforeEach [here](https://github.com/cloudfoundry/garden-shed/blob/master/layercake/docker_linux_test.go#L300-L301) and cleaned up in the "upper" BeforeEach [here](https://github.com/cloudfoundry/garden-shed/blob/master/layercake/docker_linux_test.go#L63-L64).

**Comment by williammartin** [comment] 2018-06-04 11:43
It's definitely a Ginkgo issue, not Gomega, from some initial bisecting.

**Comment by williammartin** [comment] 2018-06-04 14:55
Heyo, so this actually looks like a race in the garden-shed tests. The commit that started causing failures (5ca1211) introduced a runner that allows parallel nodes to poll a queue in order to run tests as soon as they are ready to take on work. Prior to this, if you were not using `randomizeAllSpecs` (which garden-shed isn't, see: https://github.com/cloudfoundry/garden-runc-release/blob/671960f684983a0496a05024f0db4f8203bba23d/ci/unit-tests/shed#L22) specs would get randomized across nodes per outer container (Describe / Context etc).

As such, before bumping to this commit, these two tests were never racing because they always ran sequentially on the same node. You can confirm this yourself by running the tests on the version of Ginkgo that currently works but adding `randomizeAllSpecs` and running until it fails.

I'm going to close this out now because I don't believe it's an issue with Ginkgo. Feel free to reopen if you disagree. Thanks.

**Closed by williammartin** 2018-06-04 14:55 UTC
