### ISSUE TITLE
Documentation is missing details about `When` block

### ISSUE THREAD

**Issue by harishsurf** [onsi/ginkgo#660] opened 2020-04-02 19:03 UTC
Could the documentation be updated to explain **`When`** block and it's usages? 
https://github.com/onsi/ginkgo/blob/master/ginkgo_dsl.go#L351

**Comment by ansd** [comment] 2020-04-20 21:36
Hey @harishsurf, thanks for opening this issue.
We should definitely document the `When` DSL.
Closing this issue since it's a duplicate of #420.

**Closed by ansd** 2020-04-20 21:36 UTC
