### ISSUE TITLE
AfterEach not called in case of ^C

### ISSUE THREAD

**Issue by thockin** [onsi/ginkgo#222] opened 2016-02-09 16:13 UTC
We have a BeforeEach that creates some cloud infrastructure for the test, and an AfterEach that cleans it up.  I notice that if the test is interrupted, out AfterSuite is run, but the AfterEach is not.  This causes cloud resources to leak and require manual cleanup.  Is this by design?

We have a hacky register/unregister workaround now so that AfterSuite does final cleanup, but it feels like something the test framework should be doing.

**Comment by robdimsdale** [comment] 2016-02-12 05:27
@thockin I'm not aware of that behavior, but I haven't really paid it much thought either. I can't speak to whether this is intentional or accidental - perhaps @onsi could shed some light?

On the face of it, it seems to me that your request that the test framework cleans up on both `AfterEach` and `AfterSuite` would be more intuitive and desirable.

Are there any other confounding factors here? For example are you running tests in parallel?

**Comment by thockin** [comment] 2016-02-12 06:31
Nothing else special.  I am running with a focus of a single test, but
hitting ^C goes straight to AfterSuite

**Comment by robdimsdale** [comment] 2016-02-12 15:31
I can't reproduce the behavior you describe with the latest version of ginkgo. I created a sample ginkgo test at https://github.com/robdimsdale/ginkgotest which sleeps long enough to be killed, and the output of killing that test is below:

```
Running Suite: Ginkgotest Suite
===============================
Random Seed: 1455290864
Will run 1 of 1 specs

BeforeSuite
BeforeEach
AfterEach
Inside It
sleeping
^C
---------------------------------------------------------
Received interrupt.  Running AfterSuite...
^C again to terminate immediately
AfterSuite

Ran 1 of 1 Specs in 0.458 seconds
FAIL! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
Ginkgo ran 1 suite in 1.764128937s
Test Suite Failed
```

And for reference, the output when the test is not interrupted:

```
Running Suite: Ginkgotest Suite
===============================
Random Seed: 1455290845
Will run 1 of 1 specs

BeforeSuite
BeforeEach
AfterEach
Inside It
sleeping
Completed It
• [SLOW TEST:10.006 seconds]
Ginkgotest
/Users/rdimsdale/go/src/github.com/robdimsdale/ginkgotest/ginkgotest_test.go:26
  Prints
  /Users/rdimsdale/go/src/github.com/robdimsdale/ginkgotest/ginkgotest_test.go:25
------------------------------
AfterSuite

Ran 1 of 1 Specs in 10.006 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped PASS

Ginkgo ran 1 suite in 11.327872019s
Test Suite Passed
```

What might you be doing differently to cause the behavior you observe?

**Comment by thockin** [comment] 2016-02-12 18:06
Your ginkgotest_test.go says "BeforeEach" twice.  Once that is fixed:

```
$ go test -v ./...
=== RUN   TestGinkgotest
Running Suite: Ginkgotest Suite
===============================
Random Seed: 1455300304
Will run 1 of 1 specs

BeforeSuite
BeforeEach
Inside It
sleeping
^C
---------------------------------------------------------
Received interrupt.  Running AfterSuite...
^C again to terminate immediately
AfterSuite

Ran 1 of 1 Specs in 2.039 seconds
FAIL! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped

On Fri, Feb 12, 2016 at 7:31 AM, Rob Dimsdale <notifications@github.com>
wrote:

> I can't reproduce the behavior you describe with the latest version of
> ginkgo. I created a sample ginkgo test at
> https://github.com/robdimsdale/ginkgotest which sleeps long enough to be
> killed, and the output of killing that test is below:
>
> Running Suite: Ginkgotest Suite
> ===============================
> Random Seed: 1455290864
> Will run 1 of 1 specs
>
> BeforeSuite
> BeforeEach
> AfterEach
> Inside It
> sleeping
> ^C
> ---------------------------------------------------------
> Received interrupt.  Running AfterSuite...
> ^C again to terminate immediately
> AfterSuite
>
> Ran 1 of 1 Specs in 0.458 seconds
> FAIL! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
> Ginkgo ran 1 suite in 1.764128937s
> Test Suite Failed
>
> And for reference, the output when the test is not interrupted:
>
> Running Suite: Ginkgotest Suite
> ===============================
> Random Seed: 1455290845
> Will run 1 of 1 specs
>
> BeforeSuite
> BeforeEach
> AfterEach
> Inside It
> sleeping
> Completed It
> • [SLOW TEST:10.006 seconds]
> Ginkgotest
> /Users/rdimsdale/go/src/github.com/robdimsdale/ginkgotest/ginkgotest_test.go:26
>   Prints
>   /Users/rdimsdale/go/src/github.com/robdimsdale/ginkgotest/ginkgotest_test.go:25
> ------------------------------
> AfterSuite
>
> Ran 1 of 1 Specs in 10.006 seconds
> SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
>
> Ginkgo ran 1 suite in 11.327872019s
> Test Suite Passed
>
> What might you be doing differently to cause the behavior you observe?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onsi/ginkgo/issues/222#issuecomment-183374912>.
>

**Comment by robdimsdale** [comment] 2016-02-12 19:15
@thockin you're totally correct, thanks for catching that. I've pushed a fix to my example repo.

I agree that this looks like a bug. Thoughts, @onsi ?

**Comment by onsi** [comment] 2016-02-12 21:02
Hey all, sorry for the delay.  It's true that ^C only triggers the `AfterSuite`, not any pending `AfterEach`es.  This was done intentionally, but not for any real reason other than time constraints and code quality in this part of the codebase:
https://github.com/onsi/ginkgo/blob/master/internal/specrunner/spec_runner.go

(tl;dr this part of the code is crap and I didn't have the time to untangle it to support unwinding `AfterEach`es)

It's completely doable, though, and is a great idea.  A PR would be great and I'd be happy to talk through what would be involved.

**Comment by thockin** [comment] 2016-02-12 21:34
I'm unfortunately totally buried at the moment with Kubernetes, and I don't
want to make commitments I can't follow-through on.  We have a workaround
that works but isn't really something I want to carry in the long-term.

https://github.com/thockin/kubernetes/commit/c091c63520e3c44a562740457bc62c7929ab9da1

**Comment by mangelajo** [comment] 2019-05-23 15:14
Bump, also found the same issue, while I was trying to replicate what kubernetes test do for E2E for a kubernetes network federation project.

**Comment by mangelajo** [comment] 2020-08-26 10:28
bump

**Comment by ekj1711** [comment] 2020-08-26 11:45
I am not following up on this issue, sorry!

**Comment by chrishenzie** [comment] 2020-11-04 18:23
Bumping this. @onsi (or any other contributor with context), per your previous comment, would you be able to provide a description of what would be involved in making this work?

**Comment by onsi** [comment] 2021-02-12 19:39
Happy to report this is in-scope for v2 and should be the behavior once it lands in the next couple/few months.

**Comment by onsi** [comment] 2021-04-04 03:56
This is now fixed in v2 over on the v2 branch.  It'll be a few more months before all that work ends up on master... but Ginkgo interruptions are much much cleaner now and will always try to unwind the test by running the `AfterEach`es and then the `AfterSuite`.

**Comment by onsi** [comment] 2021-09-10 19:57
A beta for Ginkgo V2 that fixes this issue was just released.   [Please try out the beta](https://github.com/onsi/ginkgo/issues/809)!

**Closed by onsi** 2021-09-10 19:57 UTC
Labels: v2
