### ISSUE TITLE
if BeforeSuite fail special test spec will not report

### ISSUE THREAD

**Issue by nkuacac** [onsi/ginkgo#196] opened 2015-11-25 06:28 UTC
Is it good to dry run test spec, if BeforeSuite fail.  Thinks

**Comment by nkuacac** [comment] 2015-11-27 03:24
because if before suite fail, it is hard to check if the test spec is fail from log

**Comment by robdimsdale** [comment] 2016-01-31 19:52
Hi @nkuacac. I'm not quite sure what you're asking here, but it sounds like you're asking about two different things.

Firstly it sounds like you are looking for advice on whether performing a dry run (with `-dryRun`) is a good idea if the `BeforeSuite` fails. I'm not sure what `-dryRun` buys you in this case. I'm not actually sure if the `BeforeSuite` is executed when `-dryRun` is provided - I assume it does not - but @onsi might be able to clarify.

Secondly, it sounds like when a failure occurs in a `BeforeSuite` you are having a hard time reading the output to determine the cause of failure. Could you provide an example output that you find difficult to read? We might be able to provide clarity on what's happening, as well as potentially improve the output.

Thanks,
Rob

**Comment by robdimsdale** [comment] 2016-03-01 02:53
@nkuacac I'm going to close this issue. Please feel free to open another one if you have further thoughts or questions.

**Closed by robdimsdale** 2016-03-01 02:53 UTC
