### ISSUE TITLE
Ginkgo CLI unfocus incorrectly modifies imports when file uses build tags

### ISSUE THREAD

**Issue by austince** [onsi/ginkgo#899] opened 2022-02-03 23:10 UTC
I think I've narrowed it down to this test case:

### Input
```go
//go:build integration

package cmd

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/austince/common-go/util"
)

var _ = FDescribe("Something", func() {
	It("should be true", func() {
		Expect(true).To(BeTrue())
		util.Must(nil)
	})
})
```

### Output

The package `github.com/austince/common-go/util` is changed to `github.com/austince/common-o/util` and the focused
describe block is unchanged. If I remove the `//go:build integration` directive, all is well.

```go
//go:build integration

package cmd

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/austince/common-o/util"
)

var _ = FDescribe("Something", func() {
	It("should be true", func() {
		Expect(true).To(BeTrue())
		util.Must(nil)
	})
})
```

## Environment

```shell
> ginkgo version
Ginkgo Version 2.1.1
```
But also tried it with 1.16 and seems to have the same issue.

**Comment by blgm** [comment] 2022-02-04 11:13
This is very curious. The way that this is mean to work is:

- the Go file is read into a buffer
- the buffer is parsed into an AST, and the position of each `FDescribe`s etc is identified
- using the positions derived from the AST, the original buffer is modified to remove the `F` characters

I was able to reproduce this with Ginkgo 1.16.4 and got `"github.com/austince/comon-go/util"` which is slightly different to what was reported above, but is essentially the same bug. I also got corruption even when the `//go:build` statement was removed, which is strange as I use this functionality on a daily basis and I've never seen it fail before.

I wonder if the character positions produced by the AST are somehow being shifted? This definitely needs a fix.

**Comment by Airblader** [comment] 2022-02-04 11:16
I've experienced this as well (disclaimer, I work with @austince) and also got it in a different spot; for me, it wasn't an import statement that got changed, but actually test code, and it happened in the CI. Needless to say I was close to questioning my sanity  when I saw

```
				Expect(ioutil.ReadAll(response.Body)).To(Eqal(payload))
				                                         ^
```

in the CI logs even though both locally and in GitHub's diff it clearly said `Equal`. :-)

**Comment by onsi** [comment] 2022-02-04 13:23
well... _faaascinating_ time for some `fmt.Println`-driven debugging.  i'm not sure that i'll be able to get to this for a few days so if anyone wants to explore it further everything is in [this file](https://github.com/onsi/ginkgo/blob/master/ginkgo/unfocus/unfocus_command.go)

**Comment by onsi** [comment] 2022-02-11 17:00
ok I'm poking around a bit.  it looks like the _length_ of the build tag changes _where_ the deletion occurs.  this says to me that something about the AST parsing is not including the build tag in the offset computations.  I'll poke around a bit more...

**Comment by austince** [comment] 2022-02-11 17:11
Thaaat would make sense (though I haven't had more than time to read through the file, sorry 😞).

**Comment by onsi** [comment] 2022-02-11 18:04
figured it out.  looks like we were incorrectly subtracting out the `file.pos()` when computing the location of the focus token.  should be fixed now... will cut a release soon.

**Closed** 2022-02-11 18:03 UTC

**Comment by Airblader** [comment] 2022-02-11 18:05
Thank you for your effort!

**Comment by blgm** [comment] 2022-02-11 20:34
Thank you @onsi
