### ISSUE TITLE
Allow reporters to write down data before panicking on timeout

### ISSUE THREAD

**Issue by lukas-bednar** [onsi/ginkgo#728] opened 2020-10-14 13:26 UTC
Hello,

When I set a timeout for entire test suite using `--timeout` parameter, the test eventually fail (panic) on given timeout - that is OK.
The issue is that I lose all data collected by reporters (junit reporter in my particular case).
My expectation is that framework can generate partial report, before panicking entire run.

Is it possible to add additional interface to the reporters to write down collected data before exiting?

**Comment by InbarRose** [comment] 2020-10-29 12:34
+1

**Comment by onsi** [comment] 2020-10-29 19:43
hmm - i might need to take a look at this but i think the fix might be a bit tricky.  the suite-level timeout parameter was always intended as a last-ditch failsafe - the expectation being that individual tests that test asynchronous behavior are written with appropriate granular timeouts (e.g. with Gomega's [`Eventually`](http://onsi.github.io/gomega/#eventually)).  My instinct is that adjusting the `--timeout` parameter down is a bit of a smell...

I appreciate that doesn't actually help solve your problem.  But I'd love to hear if it spurs any thoughts on how you're approaching the problem?

Also - if there's more detail around the underlying problem you're trying to solve with a (presumably) shorter timeout I'd love to hear it as that might help me offer alternative solutions.

For now, I'm going to add this to the [v2](https://github.com/onsi/ginkgo/issues/711) list.  v2 is [under development](https://github.com/onsi/ginkgo/projects/2) though it's been slow going...

**Comment by mat007** [comment] 2020-11-24 06:07
I have been looking for something like this because we use a custom reporter to send the test results to an elasticsearch instance. We have dozens of separate test runs occurring all day long and we use elasticsearch to query for failures and such.
When the general go test timeout hits, we miss that test run in the data.

I’ll probably try to catch the panic and force send the data with the reporter now to see how it goes.

Thanks!

**Comment by onsi** [comment] 2021-04-04 18:52
I can confirm I'm going to address this in v2.  However, I'm also considering removing support for custom reports as well in lieu of  supporting specific output formats that users can post-process.  I'm going to maintain the JUnit support and introduce a new JSON format that has all the information that currently goes to custom reporters.

@mat007 I'd like to understand how disruptive that would be for your elasticsearch reporter.  Could you (relatively) easily retool to have a post-run hook that sends the JSON report to elasticsearch instead?

**Comment by mat007** [comment] 2021-04-05 08:17
@onsi yes I think based on your description of this feature it looks fine.
Thanks!

**Comment by onsi** [comment] 2021-04-05 12:04
Glad to hear it, thanks @mat007 !

**Comment by onsi** [comment] 2021-09-30 03:32
This is now resolved in V2.  Ginkgo now manages its own timeout and triggers a test-wide interrupt that gracefully unwinds any running tests and calls reporters appropriately.  V2 is in beta and I'd love to see folks try it and give me feedback.  Docs for using the beta are [here](https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta).

**Comment by mat007** [comment] 2021-09-30 04:26
I’ve switched our e2e tests to V2 with only minor code rewrite.
It’s working fine, including in the timeout case I was describing above.

Thanks @onsi !

**Comment by onsi** [comment] 2021-09-30 11:43
that's great to hear, thanks!

**Closed** 2022-11-16 03:24 UTC
Labels: v2
