### ISSUE TITLE
ginkgo does not work running in symlinks that start with _

### ISSUE THREAD

**Issue by sharpner** [onsi/ginkgo#150] opened 2015-04-09 11:47 UTC
Hi, 

today I updated to mac os x 10.10.3 and after that, all my ginkgo testsuites fail with the following error:

```
	fork/exec path/to/some/project.test: no such file or directory
```

Anyone else having this issue?

The binary project.test got compiled and can be run manually afterwards, but the autostart does not seem to work anymore.

**Comment by sharpner** [comment] 2015-04-09 12:17
ok this seems to be on my machine only.

**Comment by sharpner** [comment] 2015-04-09 12:54
ok found the problem. If I changed to the directory via symlink, the filename differs. 

E.g. symlink hello to -> src/github.com/welcome the created binary is welcome.test but it will try to start _hello.test.

**Comment by tjarratt** [comment] 2015-04-09 14:58
Hey @sharpner this is a really weird bug. I also just upgraded to 10.10.3 and none of my ginkgo test suites are failing. Maybe you're invoking ginkgo differently than I am?

For reference, this is what I tried to reproduce what you described, as far as symlinks are concerned (but this works as expected for me)

```shell
cd ~/git/grubby
ginkgo -r . # all tests pass
cd ..
ln -s $(pwd)/grubby ~/git/grubby-test
cd grubby-test
ginkgo -r . #tests still pass
```

**Comment by sharpner** [comment] 2015-04-10 10:41
hi @tjarratt thanks for your response. 

Could you try `ln -s $(pwd)/grubby ~/git/_grubby` for me? All my symlinks start with an underscore. 

I actually have no idea what the problem might be... But for now a cd -P works for me...

**Comment by sharpner** [comment] 2015-04-10 10:42
![bildschirmfoto 2015-04-10 um 12 42 28](https://cloud.githubusercontent.com/assets/574362/7086276/1162628a-df7f-11e4-8472-cea0e61f80fe.png)

I added a screenshot for reference, maybe I'm missing something?

**Comment by tjarratt** [comment] 2015-04-10 15:21
That's pretty strange, underscores work just fine for me. I tried creating a symlink both in my home directory, and inside of my $GOPATH like you were.

```shell
tjarratt at RetinaBook in ~/git
○ ln -s $(pwd)/grubby $(pwd)/_grubby

tjarratt at RetinaBook in ~/git
○ cd _grubby/ 

tjarratt at RetinaBook in ~/git/_grubby on better-symbol-interpolation
± ginkgo -r .
[1428678835] Grubby VM Suite - 111/113 specs •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••P••••••••••••••••••••P•••••••••••••••••• SUCCESS! 49.812123ms PASS
[1428678835] Grubby Parser Suite - 256/261 specs ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••PPPPP SUCCESS! 9.696969ms PASS

Ginkgo ran 2 suites in 5.62172508s
Test Suite Passed
```

I did poke around in Ginkgo a bit and found [the code that handles finding the suites and files in the current directory](https://github.com/onsi/ginkgo/blob/master/ginkgo/testsuite/test_suite.go#L72) -- perhaps there's a subtle bug here that hasn't been caught before?

**Comment by onsi** [comment] 2015-04-10 19:29
managed to reproduce it locally -- will take a look @sharpner

**Comment by sharpner** [comment] 2015-04-11 12:22
awesome, let me know if I can help. I'm just glad it could be reproduced.

**Comment by onsi** [comment] 2015-04-14 03:21
hey @sharpner - I don't think I'm going to get to this till next week.  The issue is unrelated to the version of OS X or the underscore.  It's something to do with how Go/the kernel runs a binary with CWD set to a symlink.

I think #114 will fix this for free so I'm going to just do that.

**Comment by sharpner** [comment] 2015-04-14 08:02
sure thing. I'll update the title and remove the OS X specific name.

**Comment by onsi** [comment] 2015-05-03 17:29
aight should be fixed on master!  closing for now, please reopen if it doesn't work for you @sharpner

**Closed by onsi** 2015-05-03 17:29 UTC

**Comment by sharpner** [comment] 2015-05-04 09:38
thanks I will test it later. !
